### ISSUE TITLE
Create HTML prototype for main page

### ISSUE THREAD

**Issue by kostajh** [kostajh/drushrebuild.io#4]
With the design in #2, we should build a HTML/CSS prototype. This will help us once we want to add the JS logic on top.

**Comment by frankyonnetti** [comment]
Sounds good.

Will the code base custom? I would imagine so, just want to check with you.

**Comment by kostajh** [comment]
I'm thinking we will use Ember.js.

**Comment by frankyonnetti** [comment]
This prototype static build is ready. 
Using Bootstrap 3 for this project.

**Comment by kostajh** [comment]
@frankyonnetti :+1: Looks great!
